name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make build
        env:
          VERSION: latest
      - name: Test
        run: make test
      - name: Lint
        run: make lint
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        run: make push
        env:
          VERSION: latest
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
